{"name": "test_valid_credentials_1", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <regular.tests.test_selenium_elemental.TestLogin object at 0x10a38ac10>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"9153846b99ec2cdd5483b6b9d6156ba6\")>\n\n    @pytest.fixture\n    def login(self, driver):\n>       return login_page.LoginPage(driver)\n\nregular/tests/test_selenium_elemental.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <regular.pages.login_page.LoginPage object at 0x109fbbd90>\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"9153846b99ec2cdd5483b6b9d6156ba6\")>\n\n    def __init__(self, driver):\n        self.driver = driver\n        self._visit(\"/login\")\n>       assert self._is_displayed(self._login_form)\nE       AssertionError\n\nregular/pages/login_page.py:16: AssertionError"}, "start": 1614289494087, "stop": 1614289494087, "uuid": "84408396-4471-4a3d-ad99-80ad05848445", "historyId": "b5e39d815bd44f02945402901470a3cf", "testCaseId": "82445bd454e081b79c82aedf44dbf938", "fullName": "regular.tests.test_selenium_elemental.TestLogin#test_valid_credentials_1", "labels": [{"name": "tag", "value": "shallow"}, {"name": "parentSuite", "value": "regular.tests"}, {"name": "suite", "value": "test_selenium_elemental"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "C07ZQ0G3JYVX"}, {"name": "thread", "value": "90572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "regular.tests.test_selenium_elemental"}]}